// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-3z4iLq5WKizw9iiW0-8Q5ida3E6ffw',
    appId: '1:586723161454:web:c22500a657ed0367c3fd7f',
    messagingSenderId: '586723161454',
    projectId: 'gymbuddyalitry',
    authDomain: 'gymbuddyalitry.firebaseapp.com',
    storageBucket: 'gymbuddyalitry.firebasestorage.app',
    measurementId: 'G-3KDDXM16FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgYYY2wzEI6idbpMAUVbe1k39Tq9CpSmU',
    appId: '1:586723161454:android:f47e54ef46fcbe7fc3fd7f',
    messagingSenderId: '586723161454',
    projectId: 'gymbuddyalitry',
    storageBucket: 'gymbuddyalitry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlUYWQdZGUeJ2PuDiOkdRLMPp81NUhjJQ',
    appId: '1:586723161454:ios:816e48a1d29aa4a6c3fd7f',
    messagingSenderId: '586723161454',
    projectId: 'gymbuddyalitry',
    storageBucket: 'gymbuddyalitry.firebasestorage.app',
    iosBundleId: 'com.example.gymBuddyAliTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlUYWQdZGUeJ2PuDiOkdRLMPp81NUhjJQ',
    appId: '1:586723161454:ios:816e48a1d29aa4a6c3fd7f',
    messagingSenderId: '586723161454',
    projectId: 'gymbuddyalitry',
    storageBucket: 'gymbuddyalitry.firebasestorage.app',
    iosBundleId: 'com.example.gymBuddyAliTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-3z4iLq5WKizw9iiW0-8Q5ida3E6ffw',
    appId: '1:586723161454:web:122ad2b16e566aa9c3fd7f',
    messagingSenderId: '586723161454',
    projectId: 'gymbuddyalitry',
    authDomain: 'gymbuddyalitry.firebaseapp.com',
    storageBucket: 'gymbuddyalitry.firebasestorage.app',
    measurementId: 'G-QLQN9C7LS5',
  );
}
